### PR TITLE
use `this` global for IIFE dependencies for safe Node testing

### PR DESCRIPTION
**Pull request by larrybotha**
Running tests with babel-tape-runner when ChartistJs is a dependency within an npm link'd module throws errors because `window` and `document` are not defined in Node land.

This PR updates all occurrences of IIFEs from

``` javascript
(function(window, document, Chartist) {
  ...
}(window, document, Chartist));
```

to

``` javascript
(function(globalRoot, Chartist) {
  var window = globalRoot.window;
  var document = globalRoot.document;
  ...
}(this, Chartist));
```

### CODE REVIEW

**Comment by gionkunz** [comment]
Hi there. Thanks for the PR. Please exclude any dist files from this change. Only files in src should be added to pull requests.

**Comment by larrybotha** [comment]
@gionkunz done!

**Comment by gionkunz** [comment]
Hi there. I still see some changes in dist: https://github.com/gionkunz/chartist-js/pull/765/files

**Comment by larrybotha** [comment]
I reverted with this commit: https://github.com/gionkunz/chartist-js/pull/765/commits/bd500db6764d672b3318c87af82b122f8107ab9b but not sure why it's not reverting in the file list. I'll kill this PR and make a new one with changes to only the `src`.

**Pull request closed without merging**
