### PR TITLE
Add bower install to contribution instructions

### PR DESCRIPTION
**Pull request by JamieKnight**
Just something small I came across when following the setup instructions after a clean OS X install.

J&

### CODE REVIEW

**Comment by JamieKnight** [comment]
Hiya,

Will prod it a little more this evening.

Cheers,

Jamie + Lion

**Comment by gionkunz** [comment]
Cool stuff :+1:

**Comment by JamieKnight** [comment]
Finally home, 15 hours day including a 415 mile round trip. ouch! Will pick this one up over the weekend. For now bed!

**Comment by gionkunz** [comment]
Take your time dude :-) we all work in our freetime on this and there is no need to hurry.

**Comment by JamieKnight** [comment]
Have opened a new PR as my branch went funky.

**Pull request closed without merging**
