### PR TITLE
dual-license: WTFPL-2.0 & MIT

### PR DESCRIPTION
**Pull request by nfriedly**
Hey, this is an awesome library, and I'd like to use it in an upcoming project (and send a PR or two), but I work at IBM and some folks there get a little squirley over "unapproved" licenses. So, if you'd be willing to dual-license things with MIT as a second option, it would make my life a lot easier.

(Yes, I do realize the irony of the situation.)

### CODE REVIEW

**Comment by gionkunz** [comment]
The Free Software Foundation officially declared WTFPL 2.0 as GNU GPL compatible http://www.gnu.org/licenses/license-list.html#WTFPL

Isn't that enough for the folks at IBM? :-)

**Comment by nfriedly** [comment]
Yea... It ought to be. But this is more about ticking a box and making my life easy than it is about making sense ;)

**Comment by nfriedly** [comment]
How about a plan B: scrap this PR and keep your LICENSE file clean, and just write something along the lines of "I give IBM permission to use Chartist under the terms of the MIT license"  - would that work for you?

(Sorry for being a cooperate duchebag... but this really would make my life easier.)

**Comment by nfriedly** [comment]
Apparently they _really_ don't like the WTFPL. I ended up just going with Chart.js because of the time crunch. Hopefully I'll get to use this one at some point down the road though ;)

**Comment by gionkunz** [comment]
I switched to dual licensing WTFPL and MIT within Chartist 0.9.6 :smile: :+1:

**Comment by nfriedly** [comment]
Haha, cooperate douchbaggery for the win! Thanks! :beers:

**Pull request closed without merging**
