### PR TITLE
fix axis one record

### PR DESCRIPTION
**Pull request by jmlavoier**
This is the repair to that issue: https://github.com/gionkunz/chartist-js/issues/570

### CODE REVIEW

**Comment by joaolavoier** [comment]
@gionkunz do you will merge this pull request? Because i and others developers need this fixes. Im using my forked repository while you don't accept.

**Comment by gionkunz** [comment]
All the commits should be in the latest release

**Comment by gionkunz** [comment]
Sorry, I might have accidentally closed this PR. Can you check if this is still an issue, if yes, please submit / update your PR to only include source file changes. No dist changes are accepted. Cheers

**Comment by gionkunz** [comment]
Hi there. sorry for the delay again. Can you please include unit tests for this usecase? After having the tests we should be good to go! Thanks again for your contribution!

**Comment by erashu212** [comment]
@gionkunz : Any update on this fixes. No update in npm registry.

We are stuck here due to this fixes. Please update the npm registry so we can start moving.

**Comment by gionkunz** [comment]
I wont accept PRs which dont contain tests. Please add some unit tests that illustrate the expected behaviour.

**Comment by jmlavoier** [comment]
Hi @gionkunz, i added a test to you verify this usecase. I was looking the PR's and I found this https://github.com/gionkunz/chartist-js/pull/492 that is about the same issue.

**Comment by gionkunz** [comment]
Please resubmit this PR with concise and clean commits. Also note from the contribution guide that you should never include dist files. Thanks

**Review by gionkunz — CHANGES_REQUESTED** [review]
Squash or re-build commits

**Review by gionkunz — CHANGES_REQUESTED** [review]
Exclude dist files from commits

**Comment by jmlavoier** [comment]
Sorry my mistakes, this PR is not going good. I'll open another PR with the necessary changes to you merge. I have to close this.

**Pull request closed without merging**
