### PR TITLE
Candle stick chart implementation

### PR DESCRIPTION
**Pull request by psimonski**
Hi all,
I implemented a candle stick chart (candle.js) and added also a new example section for them.
Would be great if you find a minute to review this.
Best regards,
Simon

### CODE REVIEW

**Comment by psimonski** [comment]
Follow PR added: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16745

**Comment by psimonski** [comment]
Follow PR added: https://github.com/willsoto/ng-chartist/pull/125

**Comment by beatgammit** [comment]
What's the status on this?

**Comment by psimonski** [comment]
The review is still outstanding IMO..

**Comment by nabtron** [comment]
Can't find `src/scripts/charts/candle.js` or any related files in 0.11.0 

Was it removed?

**Comment by psimonski** [comment]
Negativ, it's part of this pull request:

https://github.com/psimonski/chartist-js/blob/cfe17c14fa1880bdb63a6633e130fc258eb6dd46/src/scripts/charts/candle.js

**Comment by danjohnso** [comment]
Hey @gionkunz, this would be a huge addition for me, any chance this could get merged?

**Comment by rszemplinski** [comment]
Any chance on this getting merged in soon?

**Comment by maxxrdrgz** [comment]
You were really close to getting the pull request merged but now it's been almost 6 months and all progress has died?

**Comment by psimonski** [comment]
I don't know why somebody can't do the review for it.. It's a "must have" in my opinion!

**Comment by Pai-Sho** [comment]
Agreed

**Comment by ghost** [comment]
+1

**Comment by beatgammit** [comment]
Another ping.

I'd be happy to attempt a PR, but I know pretty much nothing about the internals of chartist, so I don't know how good of a job I'll do. It's not a *huge* PR, and I'd really like to have this feature in the library.

**Comment by roymckenzie** [comment]
Recommend closing this PR as @gionkunz has replied to an email I sent regarding the status of this PR that there are no plans to merge this into core. He has instead encouraged @psimonski to [create a plugin](https://github.com/gionkunz/chartist-js/issues/660).

**Pull request closed without merging**
