### PR TITLE
Restructure build tasks

### PR DESCRIPTION
**Pull request by autarc**
Using seperate configuration helps organizing the process, while lazy loading the modules improves the start.

### CODE REVIEW

**Comment by gionkunz** [comment]
Hi there! Thanks so much for this PR! :-) This is overdue for a long time ;-) And actually addresses #39 . Do you think it would also make sense to group certain tasks together and have separate files for our own tasks as well? Like here https://github.com/gionkunz/frontstart/tree/master/tasks

For the changelog thing I'm still not 100% sure about what's the best approach. I'm actually not a huge fan of hiding the sausage making in my commit history. I agree that a commit should never break the system, but slowly reveal more and more functionality that, at some point, could also only partially fulfill a whole features requirements. Therefore I do appreciate small commits that group together bundles of logical units that aim towards a final feature. However, I can see the benefits of larger commits too (bisect, code review, fully working features with one commit etc.). I believe it also highly depends how transparent you'd like to be and more small commits can be great for documentation purpose too.

Let's do it like this. I'll use your branch locally and merge it with my pending things. I'll then start to use the angular changelog convention for my commits and also rebase / squash my pending stuff so it conforms more to feature commits. I'll then develop towards 0.4.2 using this format so I can see the pros / cons better.

Anyways thanks for the PR this is really great!

Cheers
Gion

**Comment by autarc** [comment]
Your're welcome :)

I saw the issue and found the monolithic setup annoying as well. Fortunately [load-grunt-config](https://github.com/firstandthird/load-grunt-config#config-grouping) already provides the tools for grouping, so it can be added straightforward.

For the changelog you are probably right - forcing people to follow a specific convention for their commits could be a problem. The problem was just that I had no clue whats the current situation of the library, as common files like CHANGELOG.md or HISTORY.md are missing. Providing a short description about the latest changes in the specific versions/patches would be great.

**Comment by gionkunz** [comment]
I think for now I'll merge the config change but let's stick to a manual changelog.md for now. I'll include one for the last few versions soon. Can you update the serve task stuff with my previous comment? Then I'll merge everything up to this commit but skip 07da672afe81964d11ba87051c8fa4661b804f4c for the moment.

Would be great to do this before any effort on #87 so I can merge it to develop and we can start a feature branch for #87 .

**Comment by gionkunz** [comment]
Hey there, did you test the site after your refactoring? When I start the site now with grunt live, there is some missing styles on the site. Maybe because of the updated deps? critical or Sass? Let me know if you need help.
screencapture-0-0-0-0-9000

**Comment by autarc** [comment]
Sorry, with the update of grunt-sass a [newer version of node-sass/libsass](https://github.com/sindresorhus/grunt-sass/commit/a7907718effdb441013341e68925a7f950666316) is used which breaks with current build. Reversed the change and like to mention the idea of seperating library and website source code in the future (#88).

**Comment by gionkunz** [comment]
Cool, I've pushed to develop (except 07da672)

**Pull request closed without merging**
