### PR TITLE
added simple tooltips to charts

### PR DESCRIPTION
**Pull request by dominicrico**
Hi,

I added simple tooltips on hover over the points, bars or slices with the current value, pre- and/or suffix text.

### CODE REVIEW

**Comment by willsoto** [comment]
I think this was already addressed in #4 with the conclusion that this sort of functionality will not be included in the core, as it is trivial to add yourself without the library.

Also, `libdist` should not be included in the PR. It is stated in [CONTRIBUTING.md](https://github.com/gionkunz/chartist-js/blob/develop/CONTRIBUTING.md) albeit in a rather inconspicuous place.

**Comment by dominicrico** [comment]
Sorry, haven't read that issue until now and the also sorry for the libdist
in PR.

**Comment by willsoto** [comment]
No big deal. It should be noted I am not a core contributor or anything, perhaps the owner will have a different thought about it.

Thanks for the PR though, glad to see this repo is getting attention.

**Comment by dominicrico** [comment]
It's great to have a easy chart library like this and in my opinion many
people would love to have "build in tooltips". This was my first try to
contribute and I learned a lot :D

**Comment by luanmuniz** [comment]
Hi guys, im new here, but here is my opinion:

You should do this feature as a library that extend chartist.js
A good way to explain my opinion is to say: This feature extend chartist.js as jquery-ui (or any plugin) extend jquery.

You can make your own repository with this code and make this feature as a extend for chartist.js
something like chartist-tooltip.js
That way, its not inside the core, but we can use in a easy way.
and OBVIOUSLY mention it here! o/

What do you guys think?

**Comment by dominicrico** [comment]
Yes, that sounds great and I was thinking about that too.

I will do this anyway, because it's a good training for me.

**Comment by gionkunz** [comment]
I agree to most points of this discussion :+1: 

Please check the advanced example I've just pushed into the gh-pages that contains a first topic of how to add behavior to Chartist from outside.

http://gionkunz.github.io/chartist-js/getting-started.html#adding-behavior-to-your-charts

Cheers
Gion

**Comment by vlasvlasvlas** [comment]
i just test the online demo found here http://gionkunz.github.io/chartist-js/getting-started.html#adding-behavior-to-your-charts the last one "ADDING BEHAVIOR TO YOUR CHARTS" with tooltips,

and at localhost i got this error:

```
Uncaught ReferenceError: $chart is not defined 

line 33: 
var $toolTip = $chart
```

my code:

```
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="libdist/chartist.min.css">
    <script src="libdist/chartist.min.js"></script>
  </head>



  <body>

<div class="ct-chart ct-perfect-fourth"></div>
  <div class="tooltip"></div>
  </body>


  <script>
  Chartist.Line('.ct-chart', {
  labels: ['1', '2', '3', '4', '5', '6'],
  series: [
    {
      name: 'Fibonacci sequence',
      data: [1, 2, 3, 5, 8, 13]
    },
    {
      name: 'Golden section',
      data: [1, 1.618, 2.618, 4.236, 6.854, 11.09]
    }
  ]
});

// $chart is set to a jQuery wrapper around the chart container div
var $toolTip = $chart
  .append('<div class="tooltip"></div>')
  .find('.tooltip')
  .hide();

$chart.on('mouseenter', '.ct-point', function() {
  var $point = $(this),
    value = $point.attr('ct:value'),
    seriesName = $point.parent().attr('ct:series-name');

  $point.animate({'stroke-width': '50px'}, 300, 'easeOutQuad');
  $toolTip.html(seriesName + '<br>' + value).show();
});

$chart.on('mouseleave', '.ct-point', function() {
  var $point = $(this);

  $point.animate({'stroke-width': '20px'}, 300, 'easeOutQuad');
  $toolTip.hide();
});

$chart.on('mousemove', function(event) {
  $toolTip.css({
    left: event.offsetX - $toolTip.width() / 2 - 10,
    top: event.offsetY - $toolTip.height() - 40
  });
});
</script>

</html>
```

whats my problem?

**Comment by dominicrico** [comment]
You have to declare $('.ct-chart') = $chart, because your $chart refers to
nothing.

**Comment by vlasvlasvlas** [comment]
Ok.. but where?

What i mean with these is, here is a public web example page http://gionkunz.github.io/chartist-js/getting-started.html#adding-behavior-to-your-charts and a simple copying of the code doesnt do the job. Maybe for better usability of examples the "show code" preview must be more real world copying code and testing. (working example)

thanks! :)

**Comment by dominicrico** [comment]
Just do it before the var $tooltip = $chart ... It has to look like
var $chart = $('.ct-chart');
var $tooltip = $chart ...

**Comment by vlasvlasvlas** [comment]
Thanks dominicrico! i do mean that working example of public "show the code" on the website would be nicer if working examples works just by copying them to localhost :) thanks for everything!! i'm so happy with this charting library!

**Comment by dominicrico** [comment]
No problem, you are welcome! Great to here it works now for you.

**Pull request closed without merging**
