### PR TITLE
Added parameter for smoothing in Line Chart

### PR DESCRIPTION
**Pull request by danieldiekmeier**
This is related to #92, but the smoothing still isn't quite what I want. (But to have full control, I'd have to set all the bezier handles myself.)

### CODE REVIEW

**Comment by gionkunz** [comment]
Hey @danieldiekmeier , Thanks so much for this PR! Can't wait to play around with this :-)

**Comment by danieldiekmeier** [comment]
This mainly adds the parameter to the method according to https://en.wikipedia.org/wiki/Cubic_Hermite_spline#Cardinal_spline

If you want to use it, you have yet to add it to the API. (I didn't want to make assumptions on how to do it)

**Comment by gionkunz** [comment]
Hmmm.... I know what you mean. I've tested a bit with big data differences and very close to the bottom of the chart. When reducing the smoothing it somehow starts to look weird and choppy. Probably we need to research more and find a more intelligent bezier smoothing algorithm
giphy

**Comment by danieldiekmeier** [comment]
Okay, so I just tried something else (in Sketch.app):

screen shot 2015-01-30 at 01 23 43

This is what it'd look like if all the handles are just horizontal, with each one reaching half way to the next node. It doesn't look quite as good as the current algorithm, but much better in the edge cases we discussed in #92. Should I have a go at this?

**Comment by gionkunz** [comment]
Hey @danieldiekmeier . I was looking at some smoothing algorithms also from D3 http://www.d3noob.org/2013/01/smoothing-out-lines-in-d3js.html and it looks like they are having the same issue with their cardinal spline smoothing. The problem is with other smoothing methods that the line is not necessarily reaching to the point and thats not okay. Thats why I appreciate catmull rome.

Your simple but cool idea to just use horizontal handles for line smoothing is actually very nice and I'd appreciate an algo like this. We could make it configurable so that one can decide which algo will be used.

D3 also offers a monotone spline http://en.wikipedia.org/wiki/Monotone_cubic_interpolation but I'm not sure if your result is actually better. Also this spline could be handy with its 3 parameters http://en.wikipedia.org/wiki/Kochanek%E2%80%93Bartels_spline . 

It would actually be nice to implement these algorithms and give the choice to the user which he wants to use.

Maybe you can give your method a shot as I think its a special case for a spline that only translates vertically. Maybe by having just vertical handles is perfect for this kind of spline.

**Comment by martinsznapka** [comment]
Morris.js does it in this way:
https://github.com/morrisjs/morris.js/blob/master/lib/morris.line.coffee#L301-L309

For comparison - Chartist.js red, Morris.js blue:
diagrams

**Comment by gionkunz** [comment]
Okay thanks @martinsznapka ! Thats exactly what @danieldiekmeier propsed but instead of half width mirror.js uses quarter width for the control points. @danieldiekeier, ill refactor the code a bit so we can make the line shmoothing function configurable. Can you then implememt your suggestion? Also it might be cool to make the control point length divisor configurable and default to 2.

**Comment by danieldiekmeier** [comment]
Sure thing! Just let me know when you're done with the refactoring.

**Comment by gionkunz** [comment]
I've closed this PR as I pushed the new interpolation module. It uses the new SVG path API. It's factory function with optional options that return functions with input path coordinates and should return an Chartist SVG path object. Let's track further progress here #92

**Pull request closed without merging**
