### PR TITLE
Monotone cubic interpolation

### PR DESCRIPTION
**Pull request by ammojamo**
See: Issue #626

The code is modelled after the existing cardinal interpolation code. For example I have used a similar splitIntoSegments() function, but with a small modification.

Actual interpolation logic is pretty straightforward to follow.

Not sure about updating tests or documentation, let me know if anything's needed.

### CODE REVIEW

**Comment by MightyPork** [comment]
Hoping this gets merged soon, it's really good!

I've patched my chartist and using this in my project, much better than the other methods.

**Comment by ammojamo** [comment]
@gionkunz Is there any issue with this PR preventing it from being merged? Anything I can do to help?

**Comment by gionkunz** [comment]
Hi there thanks for the PR! This is great! My only concerns are possible code duplication and missing tests. Maybe its time to find a general `splitIntoSegments` that goes into `Chartist.core` and can be used by cardinal as well as monotone cubic interpolation. Also tests should be written for the line chart spec. We already have a few tests that include interpolation.

**Comment by ammojamo** [comment]
Cool, I'll have a go at fixing these issues

**Comment by ammojamo** [comment]
I've now refactored `splitIntoSegments` into core (with docs and tests) and also added a test for the interpolation which uncovered a small bug, also fixed.

I noticed that the API documentation for `splitIntoSegments` doesn't get generated correctly, but this is a actually a wider issue with `dox` which is already affecting your API docs. I've submitted a PR with dox for this (https://github.com/tj/dox/pull/177)

**Comment by ammojamo** [comment]
@gionkunz Just checking if you've had a chance to review the latest changes on this PR? Let me know if anything else needs attention.

**Comment by gionkunz** [comment]
Awesome man! This looks perfect!

**Comment by gionkunz** [comment]
I believe we can get that straight in. Thanks for your work!

**Pull request merged**
