### PR TITLE
Add styles for new documentation website

### PR DESCRIPTION
**Pull request by ariarzer**

### CODE REVIEW

**Comment by gionkunz** [comment]
Hi! Thanks for the PR can you maybe add a screenshot that gives an impression of the styles so people can take a llok without installing locally? Cheers!

**Comment by dangreen** [comment]
@gionkunz https://deft-narwhal-c4182a.netlify.app

**Review by dangreen — APPROVED** [review]

**Comment by igorlukanin** [comment]
@gionkunz Do you mean a screenshot of a website (@dangreen deployed it here: https://deft-narwhal-c4182a.netlify.app/) or a screenshot of a chart added to the website?

**Comment by gionkunz** [comment]
Thanks a lot for the creation of the styles.

Heres some feedback from my side:
- I think the chartist icon should always be on yellow background. In the header it would look much better like this: 
image
- Hover color on links looks nice in the chartist red on bright background but in the header, it would be better to use the chartist yellow as the hover color.
- Something is not okay with the colors in the mobile menu: 
image
- I think we should disable the theme chooser / brightness chooser and always provide the same theme (currently the bright one). This is not a tool you're using every day but quickly check for some documentation. I think it's okay if we follow just one branding color theme.
- Currently the Prism code highlighter theme is completely different than Chartist. We have also created a code highlighter Theme on the old website which blends in very nicely. Maybe we can use the same colors?
Now: image
Old Website: 
image

**Comment by ariarzer** [comment]
I will fix your comments code highlight tomorrow 👍🏻

**Comment by ariarzer** [comment]
Hi) Sorry for waiting, I was a little bit sick. 
I done all you comments except the code highlighting. 
It seems that this is not an easy task for me, and I left it to my colleagues.

**Comment by dangreen** [comment]
@gionkunz please check out https://deft-narwhal-c4182a.netlify.app

**Comment by gionkunz** [comment]
@dangreen do you think it would be a big task to reuse the code block styles we have on the old documentation site?

**Comment by gionkunz** [comment]
@ariarzer awesome work! Thank you so much, it looks more and more like native chartist :-P

**Comment by dangreen** [comment]
@gionkunz Done https://deft-narwhal-c4182a.netlify.app.

**Comment by gionkunz** [comment]
Great thank you so much!

**Pull request merged**
