### PR TITLE
fix `this` breaking tests and builds in node environments

### PR DESCRIPTION
**Pull request by larrybotha**
This addresses https://github.com/gionkunz/chartist-js/pull/776#issuecomment-503540617.

EDIT: this PR is quite urgent, as my previous 'fix' in that PR actually introduced an issue preventing the use of Chartist in Node environments.

### CODE REVIEW

**Comment by gionkunz** [comment]
Hey there. Now theres still a change in the files, this should not be the case. Your PR should not list any changes in the dist files. Can you double check?

**Comment by larrybotha** [comment]
@gionkunz in this file list: https://github.com/gionkunz/chartist-js/pull/1177/files?

The changed files are all from `src` - where are you seeing `dist` files?

In this commit (https://github.com/gionkunz/chartist-js/pull/1177/commits/5087de37c2f597bfb66560b04ce4c583463b0d19) I've removed the built files

**Comment by gionkunz** [comment]
Sorry yes! Looks all good now! Thanks!

**Review by gionkunz — APPROVED** [review]

**Comment by larrybotha** [comment]
Nice!

My other PR addresses the core of this issue by replacing Jasmine with Jest: https://github.com/gionkunz/chartist-js/pull/1178

Some work to do on there, as the same test is failing in 2 places (something along the lines of incorrect number of grid lines being rendered in line charts and bar charts), but once I've figured out why the test is breaking this Node issue will be resolved for good.

**Comment by gionkunz** [comment]
Awesome! Im joping thatvI can spend more time on Chartist again in the near future..

**Comment by ghost** [comment]
hey could please help me regarding this issue
Uncaught TypeError: Cannot read property 'window' of undefined
As this is an error i encountered while i am shifting from my old project to new interface dashboard

**Pull request merged**
