### PR TITLE
New chart type - LineXY & DateAxis

### PR DESCRIPTION
**Pull request by baks**
New chart type proposition - LineXY and also DateAxis.

I tried to refactor code a little bit. Also created one ticks provider :)
### Line XY

``` javascript
function LineXY(query, data, options, responsiveOptions, axisX, axisY, dataTransform)
```

Example to use logarithmic scale:

``` javascript
var logTransform = function(point)
{
    return {
        x: Math.log10(point.x),
        y: point.y
    }
};

var chartlog = new Chartist.LineXY('#chart', chartData, options, responsiveOptions, axisX, axisY, logTransform);
```
### Date Axis

It allows to specify that on axis we have date values. 
We could specify resolution in DateTicksProvider constructor :
- Chartist.DateTicksProvider.Year
- Chartist.DateTicksProvider.Month
- Chartist.DateTicksProvider.Day
- Chartist.DateTicksProvider.Hour
- Chartist.DateTicksProvider.Minute
- Chartist.DateTicksProvider.Second
- Chartist.DateTicksProvider.Millisecond

If no resolution specified in DateTicksProvider constructor, ticks are created based on duration between start and end date.

example:

``` javascript
var dateAxis = new Chartist.DateAxis(Chartist.Axis.units.x,{ ticksProvider: new Chartist.DateTicksProvider(Chartist.DateTicksProvider.Hour) });
var chart = new Chartist.LineXY('#chart', chartData, options, undefined, dateAxis);
```
### Examples

[Simple LineXY](http://jsbin.com/fenihisope/2/edit)
[Logarithmic Scale](http://jsbin.com/ziwehaguqo/1/edit)
[Resolution Based Ticks Provider](http://jsbin.com/biterawama/1/edit)
[Year Ticks Provider](http://jsbin.com/geqewefuno/1/edit)
[Month Ticks Provider](http://jsbin.com/woyulonefi/2/edit)
[Day Ticks Provider](http://jsbin.com/jomituhatu/1/edit?js,output)
[Hour Ticks Provider](http://jsbin.com/nixasalobo/1/edit?html,js,output)
[Minute Ticks Provider](http://jsbin.com/waxiyozehu/1/edit?html,js,output)
[Seconds Ticks Provider](http://jsbin.com/coqoriyigi/1/edit?html,js,output)
[Milliseconds Ticks Provider](http://jsbin.com/bowuxijitu/1/edit?html,js,output)

### CODE REVIEW

**Comment by gionkunz** [comment]
Hey there! I didn't forgot about this. It will just take me some time to review and test. Please bear with me.

**Comment by Scribblets** [comment]
@baks This is perfect ~ just what we needed. However, I was wondering if there was a way to specify the x-values using the Year Ticks Provider, and then specify the y-values using the Logarthimic Scale.

Currently, there are no x values being shown at all (we would like to show every 5-10 years), and the y-values range from 4.25 - 10.25, where we would like to show incrementation in 10's: 1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, etc. etc.

Is this possible?

**Comment by baks** [comment]
I hope that this example is what you need :)

http://jsbin.com/cilovezepa/1/edit

**Comment by Scribblets** [comment]
@baks Still doesn't show anything for me. :(

**Comment by Scribblets** [comment]
screen shot 2015-04-08 at 10 01 43 am

**Comment by Scribblets** [comment]
@baks Update: So I just tested this in Firefox, and it seems to be working. I'm using Google Chrome. Is this a known issue? Is there a fix for it?

**Comment by baks** [comment]
@LRRoberts0122 You're right it doesn't work in Chrome. I try to investigate this on the weekend.

**Comment by Scribblets** [comment]
Thank you.

**Comment by baba43** [comment]
Hey @baks great work. Did you find a solution for the Chrome problem or is this request lost for now?

**Comment by baks** [comment]
@LRRoberts0122 @Baba43 I fixed problem in Chrome.
Problem was due to incorrectly calculated width value for axis label.
Hope it helps.

Sorry for that it takes so long :cry:

**Comment by gionkunz** [comment]
Hi guys, I've done a major code refactoring that unifies and encapsulates the axes much nicer. There are quite some changes and also a new axis `ContinousAxis` that allows to use ticks or a divisor to divide the range of data.

@baks Can you rework your code with the new base? There's no need to use a new chart type as the Line chart is handling the axes dynamically. They get instantiated dynamically and they have a fixed interface (you can check in the existing axes). 

As the axes are completely independent now, it would make sense to use a separate repository in cases an axis is rather complex (maybe time axis with a moment.js dependency).

I'll also work one some changes but I think the groundwork is laid.

Internally series data arrays always get normalized into multi dimensional series data like so:

```javascript
var data = [1, 2, 3]; // gets {y: 1, x: undefined, y: 2, x: undefined, y: 3, x: undefined}
```

In order to specify two dimensional data for both axes you can use this object notation of values directly.

```javascript
var data = [{x: 1, y: 100}, {x: 2, y: 120}, {x: 3, y: 140}];
```

When the values get projected, the axis will only use the value relevant for its dimension. This way you can now easily create a XY Chart with these options:

```javascript
new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3],
  series: [
    [{x: 2, y: 100}, {x: 30, y: 120}, {x: 2, y: 140}]
  ]
}, {
  fullWidth: true,
  // As this is axis specific we need to tell Chartist to use whole numbers only on the concerned axis
  axisY: {
    onlyInteger: true,
    offset: 20
  },
  axisX: {
    type: Chartist.LinearScaleAxis,
    onlyInteger: true
  }
});
```

**Comment by gionkunz** [comment]
Hi Guys, can you build the latest develop branch and help me to do some testing? be9e6b6 is now containing configurable axes and XY charts are possible. You get more info in be9e6b6 while I'm working on some further testing and documentation.

@baks if you got time, your help would be much appreciated.

**Comment by gionkunz** [comment]
@baks I'll close this PR for now and then we could do some more efforts for the date axis.

**Pull request closed without merging**
