### PR TITLE
use `this` global for IIFE dependencies for safe Node testing - round 2

### PR DESCRIPTION
**Pull request by larrybotha**
Running tests with babel-tape-runner when ChartistJs is a dependency within an npm link'd module throws errors because `window` and `document` are not defined in Node land.

This PR updates all occurrences of IIFEs from

``` javascript
(function(window, document, Chartist) {
  ...
}(window, document, Chartist));
```

to

``` javascript
(function(globalRoot, Chartist) {
  var window = globalRoot.window;
  var document = globalRoot.document;
  ...
}(this, Chartist));
```

### CODE REVIEW

**Comment by wbobeirne** [comment]
Would love to see this make it in, I'm also running in to this issue.

**Comment by gionkunz** [comment]
Sorry this took so long :(

**Comment by larrybotha** [comment]
haha, np @gionkunz - you've put far more hours into Chartist than my little PR, and I'm guessing mostly using your own time. Thanks for all the hard work; you rock! 👊

**Comment by mjamin** [comment]
This causes es2015 builds to fail as `this` is undefined.

**Comment by larrybotha** [comment]
Created this PR to address the issue: https://github.com/gionkunz/chartist-js/pull/1177

Got another branch updating tests to ensure this will never happen again. PR will be made in a day or two.

@gionkunz you're probably super busy, but this PR unfortunately didn't correct the original issue.

Would be great if you can get the new PR merged and published.

Edit: Added PR branch with refactored test frameworks: https://github.com/gionkunz/chartist-js/pull/1178

2 tests require investigation. All other tests are passing.

**Pull request merged**
