### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by breedx-splk**
Just a small typo I noticed in the docs.  Thanks for this library!

### CODE REVIEW

**Comment by JesusDeveloperX1** [comment]
Is this repo still working?

**Comment by breedx-splk** [comment]
@dimitrileite You should probably open your own issue instead of piggy-backing on this PR.

**Comment by gionkunz** [comment]
Thanks for your support! After a long break, where we only worked on critical maintenance issues, we have finally updated the stack and backbone of chartist! 🥳 Unfortunately, you must also base your PR on the latest commit.

**Comment by breedx-splk** [comment]
@gionkunz Yeah, this does look to be irrelevant now, as does #853 and #852. :) Congrats on the overhaul, phew!

**Pull request closed without merging**
