### PR TITLE
"Created" Event

### PR DESCRIPTION
**Pull request by drewbarontini**
## What is this?

This adds a new event called `created`, which is triggered once a chart is finished drawing. This is created for all three charts, and it returns:
- The `bounds`
- The `chartRect`
- The `options`
- The `svg`
## Example usage

``` javascript
var chart = new Chartist.Line('.ct-chart', {
  labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  series: [
    [12, 9, 7, 8, 5],
    [2, 1, 3.5, 7, 3],
    [1, 3, 4, 5, 6]
  ]
});

chart.on('created', function(data) {
  // ...
});
```
## Related issue

[Refs #80]

### CODE REVIEW

**Comment by drewbarontini** [comment]
@gionkunz - I might need your helping sorting out what data to pass back from the event. Currently, I just send the `type`, `labels`, and `svg`, but the `Chartist.Pie` doesn't have the same `labels`, so I pass back `seriesGroup`. Let me know what you think!

**Comment by gionkunz** [comment]
@drewbarontini, thanks for the great PR! I think so far we have included data in the event that is crucial to get the full context of the event while it occurs. In the case of the drawing events this is the index of the element, the element itself, type of the drawing ('point', 'line', 'bar' etc.).

I think for the chart created event there is almost no special context that you're not already aware from the outside and therefore I think we should stick to stuff from the closure in the create function that could be of a help in the event. For me this would be `bounds`, `chartRect`, `options` (as these were used for that specific drawing). The Pie chart is a bit special because it has no `bounds` as it operates on simple polar coordinates. Also I think we don't need the `type` field as this is only required when you have the same event with different subjects in the same chart (like draw which is triggered for labels, points, lines, slices etc.).

**Comment by drewbarontini** [comment]
Alright, I updated the returned object to include:
- The `bounds`
- The `chartRect`
- The `options`
- The `svg`

I kept the `svg` in there since there is no other place to gain access to the internally created SVG from outside, which makes it useful within the 'created' event. Let me know what you think.

**Comment by drewbarontini** [comment]
And as an example, we used it to test out creating a gradient overlay on the SVG:

``` javascript
function createGradientOverlay(svg, options) {
  var defs = svg.elem('defs');
  var grad = defs.elem(options.gradient.type, options.gradient);
  for (var stop in options.stops) {
    grad.elem('stop', options.stops[stop]);
  }
}

chart.on('created', function(data) {
  createGradientOverlay(data.svg, {
    gradient: {
      type: 'linearGradient',
      id: 'grad1'
    },
    stops: {
      1: {
        offset: '0%',
        style: 'stop-color:red;stop-opacity:1'
      },
      2: {
        offset: '100%',
        style: 'stop-color:blue;stop-opacity:1'
      }
    }
  });
});
```

**Comment by gionkunz** [comment]
Nice! :smile: 

Thanks for this guys! I'll merge that into develop straight away. I'll make a release sometime later this week.

Cheers
Gion

**Comment by drewbarontini** [comment]
:+1: Glad we could help!

**Comment by nblackburn** [comment]
@gionkunz @drewbarontini Is it possible to gain access to the series data from this event?

**Comment by gionkunz** [comment]
The data is exposed directly on the chart object. You can access it with `chart.data`. If you want to modify the data before Chartist is using it to draw, you can use the `data` event that happens before the `create` event.

**Comment by nblackburn** [comment]
My idea was to use this data to find elements over a certain value and apply a certain class to them as part of a plugin i am working on.

**Comment by gionkunz** [comment]
For this you have the ct:value attribute on each bar element. This might not be the right place to discuss further. Plase open a new issue if you need further assistance with your plugin. Cheers gion

**Pull request merged**
