### PR TITLE
fixes #537: Error on empty data set

### LINKED ISSUE #537: Error on empty data set
I get an error when I pass an empty data set.

Is it somehow possible to get an empty chart? I'd like to fill my data after page load due to lazy loading.

https://jsbin.com/wayohenane/edit?html,js,console,output

### PR DESCRIPTION
**Pull request by CrlsMrls**

### CODE REVIEW

**Comment by gionkunz** [comment]
Hey Carlos! Thanks for the PR! :-) Can we also add tests for this case?

**Comment by aTinker** [comment]
@gionkunz  - I am awaiting this fix, would be glad to add a test.

A bit stuck:

I forked, cloned, and followed the CONTRIBUTING doc - stuck at figuring out how to run the tests. 


> grunt test
Running "clean:tmp" (clean) task
>> 1 path cleaned.

Running "concurrent:test" (concurrent) task
    
    Running "sass:public" (sass) task
    
    Running "sass:dist" (sass) task
    
    Running "sass:tmp" (sass) task
    
    Done, without errors.
    
    
    Execution Time (2015-12-27 04:12:55 UTC)
    loading tasks       197ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 35%
    loading grunt-sass   14ms  ▇▇ 2%
    sass:public         167ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 30%
    sass:dist            16ms  ▇▇ 3%
    sass:tmp            172ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 30%
    Total 566ms
    
Running "connect:test" (connect) task
Started connect web server on http://localhost:9001

jit-grunt: Plugin for the "jasmine" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "jasmine" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-12-27 04:12:54 UTC)
loading tasks                  209ms  ▇▇▇▇▇▇▇▇▇▇▇▇ 17%
concurrent:test                866ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 70%
loading grunt-contrib-connect   94ms  ▇▇▇▇▇▇ 8%
connect:test                    40ms  ▇▇▇ 3%
Total 1.2s



I was hoping to see some log mentioning the tests in tests/spec/ so I can start figuring out how to add more.

**Comment by ashishUthama** [comment]
@carlos-  tried to take a crack at adding a test point:

```
it('should not error on empty series', function(done) {
  jasmine.getFixtures().set('<div class="ct-chart ct-golden-section"></div>');

var chart = new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3, 4],
  series: [[]]
});

chart.on('data', function(data) {
  expect(data.type).toEqual('initial');
  expect(data.data.series[0]).toEqual([]);
  done();
});
});
```

Results in:

```
log: Error: Problem parsing d=""
```

Maybe there is more clean up needed?

**Comment by dukex** [comment]
+1 for this PR

```
var chart = new Chartist.Line('.ct-chart', {
  labels: [],
  series: []
});
```

**Comment by gionkunz** [comment]
Ideally all those calls would result in a valid chart: `new Chartist.Line('.ct-chart', {labels: [], series: []})` or `new Chartist.Line('.ct-chart', {labels: [1, 2, 3, 4]})` or `new Chartist.Line('.ct-chart')`

**Comment by CrlsMrls** [comment]
Similarly as @aTinker pointed out, I created the following test:

``` javascript
describe('Meta data tests', function () {
    it('should generate no error when no data', function(done) {
      jasmine.getFixtures().set('<div class="ct-chart"></div>');

      var data = {
        labels: [],
        series: [[]]
      };

      var chart = new Chartist.Line('.ct-chart', data);

      expect(function() {
        chart.on('created', function() {
          done();
        });
      }).not.toThrow();
    });
```

BUT when running `grunt test`, I get the following lines:

```
   Meta data tests
     - should generate no error when no data...
log: Error: Problem parsing d=""
     ✓ should generate no error when no data
```

Which confuses me because:
- Test does not pass nor generates error :hushed: 
- On Chrome there is no such log error :confused: 
- This log error happens at the following test case :astonished:  

@gionkunz, what do you think?

**Comment by gionkunz** [comment]
I guess that's the SVG parser throwing this error when he tries to render the path and the path d attribute is not in the right format. The problem is that I think this exception is not thrown by the SVG parser but logged into the console AFAIK. Maybe you can debug log the SVG module to see whats the value of the d path attribute at this point. I'll take a look at the branch when I find time next week.

**Comment by gionkunz** [comment]
We should also add tests for all different axis types http://gionkunz.github.io/chartist-js/getting-started.html#switching-axis-type

**Comment by gionkunz** [comment]
I've put some additional logic on top to fulfill #598. Thanks for your efforts!

**Pull request merged**
