### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by willsoto**
As promised in #5, here is `CONTRIBUTING.md` 

I tried to distill your comment into things I felt contributors would need to know. Hopefully I covered everything. If you'd like anything else noted, feel free to let me know.

### CODE REVIEW

**Comment by luanmuniz** [comment]
:+1: \o/

**Comment by gionkunz** [comment]
Thanks again for the update! Yeah, let's see where this is going. As long as the code stays clean and maintainable I would not see a problem in switching to a more OO like architecture in the future if needed.

Can you as a last step maybe also include the priorities of things that need to be done next? I've listed them already in the README. After this I'll accept the pull request, and thanks again for your work!

Cheers
Gion

**Comment by willsoto** [comment]
Done! :D

**Comment by gionkunz** [comment]
Cool thanks! :+1: An congratulates for the first alien commit after 217 smug commits of my own :tongue:

**Comment by willsoto** [comment]
Thanks for accepting. Hoping it's the first of many. :)

**Pull request merged**
